[[news]]
date = "2025-05"
content = "Joined Hopkins Computational Imaging Group as a graduate research student."

[[news]]
date = "2024-09"
content = "Started my Master's at JHU, Baltimore, United States, and joined Yi Lab as a graduate research student."

[[news]]
date = "2024-06"
content = "Graduated from SUSTech and received my Bachelor's degree."

[[news]]
date = "2023-07"
content = "Joined Dr. Kawal Rhode's group at King's College London as an undergraduate summer research student."

[[news]]
date = "2023-01"
content = "Started my internship in MGI Tech Co., Ltd."


[[news]]
date = "2021-09"
content = "Joined Bio-Optic and Acoustic Technology Lab as an undergraduate research student."

[[news]]
date = "2020-09"
content = "Started my Bachelor's at SUSTech, Shenzhen, China."

